services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
    depends_on:
        - db
  db:
    image: mongo:5.0-focal
    volumes:
      - ./mongo:/data/db