services:
  web:
    build:
      context: .
      dockerfile: wait-for-it.Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
    depends_on:
        - db
    command: ["./wait-for-it.sh", "db:27017", "--", "python", "app.py" ]
  db:
    image: mongo:5.0-focal
    volumes:
      - ./mongo:/data/db